server:
  port: 33688

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/jinshan?serverTimezone=UTC
#    username: root
#    password: java

spring:
  datasource:
    druid:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@31.8.17.44:1521/data_dashboard
      username: JINSHANXYZ
      password: JINSHANXYZ

file:
  unZipPath: D:/gaode/zip/
  outPath:  D:/gaode/data/